name: covid_ph_tracker
dependencies:
    - python=3.8
    - pip:
        - dash
        - dash-bootstrap-components
        - dash-core-components
        - dash-html-components
        - dash-table
        - pandas
        - plotly
        - gunicorn
